#############################9/19/2018
setwd("C:/Users/hanyi_gm/Desktop/第五学期/Data Mining")
data <- read.csv("usedcars(1).csv")
var(data$price)
var(data$model)
table(data$year)
table(data$model)
model_table <- table(data$model)
prop.table(model_table)
help("prop.table")
color_table <-table(data$color)
color_pct <- prop.table(color_table)*100
round(color_pct,digits = 1)
plot(x = data$mileage,y = data$price,main = "price & maileage", xlab = "mi()",ylab = "pri($)")
data$buzhidao <- data$ color %in% c("Black","Grey","White","Yellow")
data$buzhidao[1:100]
table(data$buzhidao)
install.packages("gmodels")
library("gmodels")
CrossTable(x= data$model,y=data$buzhidao)
install.packages("yaml")
CrossTable(x= data$model, y=data$buzhidao)
help("CrossTable")
housing.df <- read.csv("BostonHousing(1).csv")
str(housing.df)
plot(housing.df$MEDV~housing.df$LSTAT,xlab="lstat",ylab="medv")
install.packages("ggplot")
library("ggplot")
install.packages("ggplot2")
library("ggplot2")
ggplot(housing.df) + geom_point(aes(x= LSTAT,y= MEDV),color = "pink", alpha = 0.69)
nhousing <- aggregate(housing.df$MEDV, by = list(housing.df$CHAS), FUN = mean)
names(nhousing) <- c("CHAS","MeanMEDV")
barplot(nhousing$MeanMEDV, names.arg = nhousing$CHAS, xlab = "CHAS", ylab = "AVG.MEDV")
ggplot(nhousing) + geom_bar(aes(x = CHAS, y = MeanMEDV), stat = "identity")
hist(housing.df$MEDV,xlab = "MEDV")
ggplot(housing.df)+ geom_histogram(aes(x = MEDV),binwidth = 9)
boxplot(housing.df$MEDV ~ housing.df$CHAS,X= "chas", y = "medv")
ggplot(housing.df) + geom_boxplot(aes(x = as.factor(CHAS),y = MEDV))+ xlab("CHAS")
par(mfcol =c(2,2))
boxplot(housing.df$NOX ~ housing.df$CAT..MEDV,xlab = "CAT.MEDV", ylab = "yeah")
boxplot(housing.df$NOX ~ housing.df$CAT..MEDV,xlab = "CAT.MEDV", ylab = "yeah")
boxplot(housing.df$NOX ~ housing.df$CAT..MEDV,xlab = "CAT.MEDV", ylab = "yeah")
boxplot(housing.df$NOX ~ housing.df$CAT..MEDV,xlab = "CAT.MEDV", ylab = "yeah")
par(mfcol = c(1,1))#put different picture into one plot
heatmap
heatmap(cor(housing.df),Rowv = NA, Colv = NA)
plot(housing.df$NOX ~ housing.df$LSTAT,ylab = "nox",
     xlab ="kuai",col=ifelse(housing.df$CAR.MEDV==1,"blue","red"))
legend("topleft",inset = c(0,-0.2),legend = c("CAT.MEDV == 1","CAT.MEDV =0"), col = c("blue","red"),
       pch =1, cex = 0.5)
ggplot(meltedshang,aes(x = X1, y = X2, fill = value)) +geom_text(aes(x = X1,y = X2,label = value))
ggplot(housing.df,aes(y = NOX, X=LSTAT, colour = CAT.MEDV))+ geom_point(alpha = 0.6)
ls(housinf.df)
plot(housing.df,c(1,3,12,13))
install.packages("GGally")
library("GGally")
ggpairs(housing.df[c(1,3,12,13)])
options(scipon = 999)
plot(housing.df$MEDV ~ housing.df$CRIM,xlab = "crim", ylab ="medv",log = 'xy')
ggplot(housing.df) + geom_point(aes(x = CRIM,y = MEDV))+ scale_x_log10(breaks = 10^(-2:2),
    labels = format(10^(-2:2),scientific = FALSE,drop0trailing = TRUE)) + scale_y_log10(breaks = c(5,10,20,40)) 
boxplot(housing.df$CRIM ~ housing.df$CAT..MEDV,xlab = "cat..medv", ylab = "nima")
boxplot(housing.df$CRIM ~ housing.df$CAT..MEDV,xlab = "cat..medv", ylab = "nima",log = 'y')
library(MASS)
par(mfol=c(2,1))
parcoord(housinf.df[housinf.df$CAT..MEDV ==0,-14], main="CAT..MEDV =0")
parcoord(housinf.df[housinf.df$CAT..MEDV ==1,-14], main="CAT..MEDV =1")
install.packages("igraph")
library("igraph")
ebay <- read.csv("ebaynetwork.csv")
eaby1 <- as.factor(ebay[,1])
eaby2 <- as.factor(ebay[,2])
graph1 <- as.matrix(ebay[,1:2])
g <- graph.edgelist(graph1,directed = FALSE)
